#!/bin/bash
# 交易机器人配置文件
# 为每个交易所定义独立的启动参数

# ========================================
# 通用日志管理配置 (适用于所有交易所)
# ========================================
LOG_MAX_SIZE_MB=50                    # 单个日志文件最大大小(MB)
LOG_KEEP_DAYS=2                      # 保留历史日志天数
LOG_COMPRESS=true                     # 是否压缩历史日志
LOG_AUTO_CLEANUP=true                 # 是否自动清理旧日志
LOG_ROTATION_ENABLED=true             # 是否启用日志轮转
LOG_APPEND_MODE=true                  # 是否使用追加模式(true=追加, false=覆盖)
LOG_CLEANUP_ON_START=false            # 启动时是否清理旧日志

# ========================================
# 交易所特定配置
# ========================================

# Paradex 交易所配置
PARADEX_TICKER="BTC"
PARADEX_QUANTITY="0.005"
PARADEX_TAKE_PROFIT="0.002"
PARADEX_DIRECTION="buy"
PARADEX_MAX_ORDERS="20"
PARADEX_WAIT_TIME="450"
PARADEX_GRID_STEP="0.05"
PARADEX_STOP_PRICE="-1"
PARADEX_PAUSE_PRICE="-1"
PARADEX_ASTER_BOOST="false"
PARADEX_ENV_PATH="./para_env"
PARADEX_ENV_FILE=".env"
PARADEX_LOG_FILE="logs/paradex_output.log"
PARADEX_PID_FILE="logs/.paradex_pid"
PARADEX_ENABLE_DRAWDOWN_MONITOR="true"
PARADEX_DRAWDOWN_LIGHT_THRESHOLD="3"
PARADEX_DRAWDOWN_MEDIUM_THRESHOLD="5"
PARADEX_DRAWDOWN_SEVERE_THRESHOLD="8"

# GRVT 交易所配置
GRVT_TICKER="BTC"
GRVT_QUANTITY="0.005"
GRVT_TAKE_PROFIT="0.00"
GRVT_DIRECTION="buy"
GRVT_MAX_ORDERS="20"
GRVT_WAIT_TIME="450"
GRVT_GRID_STEP="0.03"
GRVT_STOP_PRICE="-1"
GRVT_PAUSE_PRICE="-1"
GRVT_ASTER_BOOST="false"
GRVT_ENV_PATH="./env"
GRVT_ENV_FILE=".env"
GRVT_LOG_FILE="logs/grvt_output.log"
GRVT_PID_FILE="logs/.grvt_pid"
GRVT_ENABLE_DRAWDOWN_MONITOR="true"
GRVT_DRAWDOWN_LIGHT_THRESHOLD="3"
GRVT_DRAWDOWN_MEDIUM_THRESHOLD="5"
GRVT_DRAWDOWN_SEVERE_THRESHOLD="8"

# Extended (X10) 交易所配置
EXTENDED_TICKER="BTC"
EXTENDED_QUANTITY="0.005"
EXTENDED_TAKE_PROFIT="0.002"
EXTENDED_DIRECTION="buy"
EXTENDED_MAX_ORDERS="20"
EXTENDED_WAIT_TIME="450"
EXTENDED_GRID_STEP="0.03"
EXTENDED_STOP_PRICE="-1"
EXTENDED_PAUSE_PRICE="-1"
EXTENDED_ASTER_BOOST="false"
EXTENDED_ENV_PATH="./env"
EXTENDED_ENV_FILE=".env"
EXTENDED_LOG_FILE="logs/extended_output.log"
EXTENDED_PID_FILE="logs/.extended_pid"
EXTENDED_ENABLE_DRAWDOWN_MONITOR="true"
EXTENDED_DRAWDOWN_LIGHT_THRESHOLD="3"
EXTENDED_DRAWDOWN_MEDIUM_THRESHOLD="5"
EXTENDED_DRAWDOWN_SEVERE_THRESHOLD="8"

# Lighter 交易所配置
LIGHTER_TICKER="HYPE"
LIGHTER_QUANTITY="0.5"
LIGHTER_TAKE_PROFIT="0.002"
LIGHTER_DIRECTION="buy"
LIGHTER_MAX_ORDERS="100"
LIGHTER_WAIT_TIME="450"
LIGHTER_GRID_STEP="0.05"
LIGHTER_STOP_PRICE="-1"
LIGHTER_PAUSE_PRICE="-1"
LIGHTER_ASTER_BOOST="false"
LIGHTER_ENV_PATH="./env"
LIGHTER_ENV_FILE=".env"
LIGHTER_LOG_FILE="logs/lighter_output.log"
LIGHTER_ENABLE_DRAWDOWN_MONITOR="true"
LIGHTER_DRAWDOWN_LIGHT_THRESHOLD="2"
LIGHTER_DRAWDOWN_MEDIUM_THRESHOLD="3"
LIGHTER_DRAWDOWN_SEVERE_THRESHOLD="5"

# 可以根据需要添加更多交易所配置
# 例如：
# BACKPACK_TICKER="ETH"
# BACKPACK_QUANTITY="0.01"
# BACKPACK_TAKE_PROFIT="0.006"
# BACKPACK_DIRECTION="buy"
# BACKPACK_MAX_ORDERS="25"
# BACKPACK_WAIT_TIME="600"
# BACKPACK_GRID_STEP="0.12"
# BACKPACK_STOP_PRICE="-1"
# BACKPACK_PAUSE_PRICE="-1"
# BACKPACK_ASTER_BOOST="false"
# BACKPACK_ENV_PATH="./env"
# BACKPACK_ENV_FILE=".env"
# BACKPACK_LOG_FILE="backpack_output.log"
# BACKPACK_ENABLE_DRAWDOWN_MONITOR="true"
# BACKPACK_DRAWDOWN_LIGHT_THRESHOLD="5"
# BACKPACK_DRAWDOWN_MEDIUM_THRESHOLD="8"
# BACKPACK_DRAWDOWN_SEVERE_THRESHOLD="12"